version: '3.8'

services:
  iam-service:
    build:
      context: ./services/iam-service
    volumes:
      - ./services/iam-service:/var/www/html/iam
      - ./infrastructure/jwt:/var/www/html/iam/config/jwt:ro
      - ./services/iam-service/var/log:/var/www/html/iam/var/log
    depends_on:
      - db
      - rabbitmq
      - keycloak
    networks:
      - lms-network
  
  course-service:
    build:
      context: ./services/course-service
    volumes:
      - ./services/course-service:/var/www/html/course
      - ./infrastructure/jwt:/var/www/html/course/config/jwt:ro
      - ./services/course-service/var/log:/var/www/html/course/var/log
    networks:
      - lms-network
  
  payment-service:
    build:
      context: ./services/payment-service
    volumes:
      - ./services/payment-service:/var/www/html/payment
      - ./infrastructure/jwt:/var/www/html/payment/config/jwt:ro
      - ./services/payment-service/var/log:/var/www/html/payment/var/log
    networks:
      - lms-network

  enrollment-service:
    build:
      context: ./services/enrollment-service
    volumes:
      - ./services/enrollment-service:/var/www/html/enrollment
      - ./infrastructure/jwt:/var/www/html/enrollment/config/jwt:ro
      - ./services/enrollment-service/var/log:/var/www/html/enrollment/var/log
    networks:
      - lms-network

  notification-service:
    build:
      context: ./services/notification-service
    volumes:
      - ./services/notification-service:/var/www/html/notification
      - ./infrastructure/jwt:/var/www/html/notification/config/jwt:ro
      - ./services/notification-service/var/log:/var/www/html/notification/var/log
    depends_on:
      - db
      - rabbitmq
    networks:
      - lms-network

  notification-worker:
    build:
      context: ./services/notification-service
    command: php bin/console messenger:consume iam_events -vv --time-limit=3600
    volumes:
      - ./services/notification-service:/var/www/html/notification
    depends_on:
      - db
      - rabbitmq
      - notification-service
    restart: unless-stopped
    networks:
      - lms-network
  
  assessment-service:
    build:
      context: ./services/assessment-service
    volumes:
      - ./services/assessment-service:/var/www/html/assessment
      - ./infrastructure/jwt:/var/www/html/assessment/config/jwt:ro
      - ./services/assessment-service/var/log:/var/www/html/assessment/var/log
    networks:
      - lms-network

  nginx-gateway:
    image: nginx:alpine
    container_name: lms-nginx-gateway
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - iam-service
      - keycloak
      - course-service
    networks:
     - lms-network

  db:
    image: postgres:15-alpine
    container_name: lms-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    networks:
      - lms-network
  
  redis:
    image: redis:alpine
    container_name: lms-redis
    ports:
      - "6379:6379"
    networks:
      - lms-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lms-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Giao diện web UI
    networks:
      - lms-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: lms-keycloak
    command: start-dev --import-realm
    volumes:
      - ./infrastructure/keycloak/import:/opt/keycloak/data/import
      - ./infrastructure/keycloak/themes:/opt/keycloak/themes
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_SPI_EMAIL_SENDER_DEFAULT_MAIL_SMTP_SSL_PROTOCOLS: TLSv1.2 TLSv1.3
      KC_SPI_EMAIL_SENDER_DEFAULT_MAIL_SMTP_SSL_TRUST: smtp.gmail.com

      # KC_SMTP_HOST: ${KC_SMTP_HOST}
      # KC_SMTP_PORT: ${KC_SMTP_PORT}
      # KC_SMTP_FROM: ${KC_SMTP_FROM}
      # KC_SMTP_AUTH: ${KC_SMTP_AUTH}
      # KC_SMTP_USER: ${KC_SMTP_USER}
      # KC_SMTP_PASSWORD: ${KC_SMTP_PASSWORD}
      # KC_SMTP_STARTTLS: ${KC_SMTP_STARTTLS}
      # KC_SMTP_SSL: ${KC_SMTP_SSL}

      KC_SMTP_HOST: ${KC_SMTP_HOST}
      KC_SMTP_PORT: ${KC_SMTP_PORT}
      KC_SMTP_FROM: ${KC_SMTP_FROM}
      KC_SMTP_AUTH: ${KC_SMTP_AUTH}
      KC_SMTP_STARTTLS: ${KC_SMTP_STARTTLS}
      KC_SMTP_SSL: ${KC_SMTP_SSL}
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - lms-network

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - lms-network
    
  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ./var/lib/docker/containers:/var/lib/docker/containers:ro
  #   command: -config.file=/etc/promtail/config.yaml

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - lms-network
networks:
  lms-network:
    driver: bridge