services:
  iam-service:
    build:
      context: ./services/iam-service
    volumes:
      - ./services/iam-service:/var/www/html
    networks:
      - lms-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./services/iam-service:/var/www/html
      - ./services/iam-service/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - iam-service
    networks:
      - lms-network
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    networks:
      - lms-network
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - lms-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lms-network
  
networks:
  lms-network:
    driver: bridge