location /api/notification {
    rewrite ^/api/notification/?(.*)$ /$1 break;
    
    fastcgi_pass notification-service:9000;
    include fastcgi_params;
    
    fastcgi_param REQUEST_URI $uri;
    
    fastcgi_param REMOTE_ADDR $remote_addr; 
    fastcgi_param SCRIPT_FILENAME /var/www/html/notification/public/index.php;
    fastcgi_intercept_errors on;
}