# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    keycloak_url: '%env(KEYCLOAK_URL)%'
    client_id: '%env(CLIENT_ID)%'
    client_secret: '%env(CLIENT_SECRET)%'
    grant_type: '%env(GRAND_TYPE)%'
    scope: '%env(SCOPE)%'
    frontend_url: '%env(FRONTEND_URL)%'
    keycloak_webhook_secret: '%env(KEYCLOAK_WEBHOOK_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Security\JwtFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

    Lms\Shared\EventSubscriber\ApiExceptionSubscriber:
        arguments:
            $debug: '%kernel.debug%'

    Lms\Shared\Logger\BaseLogService:
        arguments:
            $service: 'iam-service'

    App\Service\RegisterService:
        arguments:
            $keycloakUrl: '%keycloak_url%'
            $frontendUrl: '%frontend_url%'

    App\Service\KeycloakAdminService:
        arguments:
            $keycloakUrl: '%keycloak_url%'
            $clientId: '%client_id%'
            $clientSecret: '%client_secret%'

    App\Service\ForgotPasswordService:
        arguments:
            $frontendUrl: '%frontend_url%'

    App\Service\KeycloakActionTokenValidator:
        arguments:
            $publicKeyPath: '%kernel.project_dir%/config/jwt/keycloak-public.pem'

    App\Service\KeycloakClaimsReader:
        arguments:
            $clientId: '%client_id%'
