lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    # Quan trọng: Cấu hình để lấy claim nào làm User Identifier (ví dụ 'sub' hoặc 'email')
    user_id_claim: email 
    clock_skew: 0