lexik_jwt_authentication:
    # Cấu hình Key giải mã
    public_key: '%kernel.project_dir%/config/jwt/keycloak-public.pem'
    secret_key: '%kernel.project_dir%/config/jwt/keycloak-public.pem' 

    # Định nghĩa thuật toán RS256 của Keycloak
    encoder:
        signature_algorithm: RS256

    # Chỉ định claim chứa username trong JWT Payload của Keycloak
    user_id_claim: preferred_username

    # Trích xuất token từ Cookie
    token_extractors:
        cookie:
            enabled: true
            name: auth_token